version: '3'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: install-script-cont
    volumes:
      - ~/.dotfiles/scripts/scripts/install:/install
    stdin_open: true
    tty: true
    command: ["/usr/bin/env", "bash"]
